spring:
  datasource:
#    url: jdbc:h2:mem:testdb
    url: jdbc:h2:file:./db/urlDBTest
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false
      
# Purge cron configuration properties
# timeout in minutes
url-purge:
    timeout: 5