server:
  port: 5000

spring:
  application:
    name: url-shortening-service
  datasource:
#    url: jdbc:h2:mem:testdb
    url: jdbc:h2:file:./db/urlDB
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      
# Purge cron configuration and timeout (minutes) properties
url-purge:
  timeout: 30
  cronexpression: 0 0/1 * * * ?